// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/IBM/ibmcloud-storage-volume-lib/volume-providers/vpc/metrics"
)

type HistogramMetric struct {
	RegisterMetricStub        func(registerer prometheus.Registerer)
	registerMetricMutex       sync.RWMutex
	registerMetricArgsForCall []struct {
		registerer prometheus.Registerer
	}
	ObserveValueStub        func(labels metrics.MetricLabels, value float64)
	observeValueMutex       sync.RWMutex
	observeValueArgsForCall []struct {
		labels metrics.MetricLabels
		value  float64
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *HistogramMetric) RegisterMetric(registerer prometheus.Registerer) {
	fake.registerMetricMutex.Lock()
	fake.registerMetricArgsForCall = append(fake.registerMetricArgsForCall, struct {
		registerer prometheus.Registerer
	}{registerer})
	fake.recordInvocation("RegisterMetric", []interface{}{registerer})
	fake.registerMetricMutex.Unlock()
	if fake.RegisterMetricStub != nil {
		fake.RegisterMetricStub(registerer)
	}
}

func (fake *HistogramMetric) RegisterMetricCallCount() int {
	fake.registerMetricMutex.RLock()
	defer fake.registerMetricMutex.RUnlock()
	return len(fake.registerMetricArgsForCall)
}

func (fake *HistogramMetric) RegisterMetricArgsForCall(i int) prometheus.Registerer {
	fake.registerMetricMutex.RLock()
	defer fake.registerMetricMutex.RUnlock()
	return fake.registerMetricArgsForCall[i].registerer
}

func (fake *HistogramMetric) ObserveValue(labels metrics.MetricLabels, value float64) {
	fake.observeValueMutex.Lock()
	fake.observeValueArgsForCall = append(fake.observeValueArgsForCall, struct {
		labels metrics.MetricLabels
		value  float64
	}{labels, value})
	fake.recordInvocation("ObserveValue", []interface{}{labels, value})
	fake.observeValueMutex.Unlock()
	if fake.ObserveValueStub != nil {
		fake.ObserveValueStub(labels, value)
	}
}

func (fake *HistogramMetric) ObserveValueCallCount() int {
	fake.observeValueMutex.RLock()
	defer fake.observeValueMutex.RUnlock()
	return len(fake.observeValueArgsForCall)
}

func (fake *HistogramMetric) ObserveValueArgsForCall(i int) (metrics.MetricLabels, float64) {
	fake.observeValueMutex.RLock()
	defer fake.observeValueMutex.RUnlock()
	return fake.observeValueArgsForCall[i].labels, fake.observeValueArgsForCall[i].value
}

func (fake *HistogramMetric) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.registerMetricMutex.RLock()
	defer fake.registerMetricMutex.RUnlock()
	fake.observeValueMutex.RLock()
	defer fake.observeValueMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *HistogramMetric) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ metrics.HistogramMetric = new(HistogramMetric)
