- testCase: "Create and delete VPC volume [profile: tier-3iops]"
  input:
    volume:
      name: e2e-storage-volume-3iops
      capacity: 10
      profile: tier-3iops
      iops: 0
      tags: "Testing VPC volume from library with tier-3iops profile"
  success: true
- testCase: "Create and delete VPC volume [profile: tier-5iops]"
  input:
    volume:
      name: e2e-storage-volume-5iops
      capacity: 10
      profile: tier-5iops
      iops: 0
      tags: "Testing VPC volume from library with tier-5iops profile"
  success: true
- testCase: "Create and delete VPC volume [profile: tier-10iops]"
  input:
    volume:
      name: e2e-storage-volume-10iops
      capacity: 50
      profile: tier-10iops
      iops: 0
      tags: "Testing VPC volume from library with tier-10iops profile"
  success: true
- testCase: "Create and delete VPC volume [profile: custom]"
  input:
    volume:
      name: e2e-storage-volume-custom
      capacity: 10
      profile: custom
      iops: 1000
      tags: "Testing VPC volume from library with custom profile"
  success: true
  skip : true
- testCase: "Create and delete VPC volume with encryption"
  input:
    volume:
      name: e2e-storage-volume-5iops-encryption
      capacity: 100
      profile: tier-5iops
      iops: 0
      tags: "Testing VPC volume from library with with encryption"
    encryptionKey: "crn:v1:bluemix:public:kms:eu-gb:a/b661e758bf044d2d928fef7900d5130b:0ce5fa89-18ee-4176-add8-4a340c538076:key:9957a976-bda3-47ca-b773-54ec73316b1d"
  success: true
  skip : true
- testCase: "Create and delete VPC volume access point"
  input:
    volume:
      name: e2e-storage-volume-5iops
      capacity: 10
      profile: tier-5iops
      iops: 0
      tags: "Testing VPC volume from library with tier-5iops profile"
    vpcID:
    - r018-915c1b93-604e-48e3-b285-1c3f99314349
  success: true
- testCase: "Create and delete VPC volume access point for invalid VPC ID"
  input:
    volume:
      name: e2e-storage-volume-5iops
      capacity: 10
      profile: tier-5iops
      iops: 0
      tags: "Testing VPC volume from library with tier-5iops profile"
    vpcID:
    - r018-915c1b93-604e-48e3-b285-1c3f993142424
  success: false
- testCase: "Create and delete VPC volume access point"
  input:
    volume:
      name: e2e-storage-volume-5iops
      capacity: 10
      profile: tier-5iops
      iops: 0
      initialOwner: true
      tags: "Testing VPC volume from library with tier-5iops profile"
    vpcID:
    - r018-915c1b93-604e-48e3-b285-1c3f99314349
  success: true
  skip: true
- testCase: "Create and delete VPC volume with invalid profile"
  input:
    volume:
      name: e2e-storage-volume-5iops-invalid
      capacity: 10
      profile: 20iops-tier
      iops: 0
      tags: "Testing VPC volume from library with invalid profile"
  success: false
- testCase: "Create and delete VPC volume invalid volume name"
  input:
    volume:
      name: "!#$#$#$sdwd"
      capacity: 10
      profile: tier-5iops
      iops: 0
      tags: "Testing VPC volume from library with invalid volume name"
  success: false
- testCase: "Create and delete VPC volume with invalid custom iops"
  input:
    volume:
      name: e2e-storage-volume-custom-invalid
      capacity: 10
      profile: custom
      iops: 2000
      tags: "Testing VPC volume from library with invalid custom iops"
  success: false
  skip : true
- testCase: "Create and delete VPC volume with invalid encryption key"
  input:
    volume:
      name: e2e-storage-volume-5iops-invalid-encryption
      capacity: 10
      profile: tier-5iops
      iops: 0
      tags: "Testing VPC volume from library with with invalid encryption"
    encryptionKey: "ssasadad"
  success: false
  skip : true