// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	sync "sync"

	backend "github.com/IBM/ibmcloud-storage-volume-lib/volume-providers/softlayer/backend"
	datatypes "github.com/softlayer/softlayer-go/datatypes"
)

type BillingOrderService struct {
	FilterStub        func(string) backend.BillingOrderService
	filterMutex       sync.RWMutex
	filterArgsForCall []struct {
		arg1 string
	}
	filterReturns struct {
		result1 backend.BillingOrderService
	}
	filterReturnsOnCall map[int]struct {
		result1 backend.BillingOrderService
	}
	GetAllObjectsStub        func() ([]datatypes.Billing_Order, error)
	getAllObjectsMutex       sync.RWMutex
	getAllObjectsArgsForCall []struct {
	}
	getAllObjectsReturns struct {
		result1 []datatypes.Billing_Order
		result2 error
	}
	getAllObjectsReturnsOnCall map[int]struct {
		result1 []datatypes.Billing_Order
		result2 error
	}
	GetObjectStub        func() (datatypes.Billing_Order, error)
	getObjectMutex       sync.RWMutex
	getObjectArgsForCall []struct {
	}
	getObjectReturns struct {
		result1 datatypes.Billing_Order
		result2 error
	}
	getObjectReturnsOnCall map[int]struct {
		result1 datatypes.Billing_Order
		result2 error
	}
	IDStub        func(int) backend.BillingOrderService
	iDMutex       sync.RWMutex
	iDArgsForCall []struct {
		arg1 int
	}
	iDReturns struct {
		result1 backend.BillingOrderService
	}
	iDReturnsOnCall map[int]struct {
		result1 backend.BillingOrderService
	}
	MaskStub        func(string) backend.BillingOrderService
	maskMutex       sync.RWMutex
	maskArgsForCall []struct {
		arg1 string
	}
	maskReturns struct {
		result1 backend.BillingOrderService
	}
	maskReturnsOnCall map[int]struct {
		result1 backend.BillingOrderService
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *BillingOrderService) Filter(arg1 string) backend.BillingOrderService {
	fake.filterMutex.Lock()
	ret, specificReturn := fake.filterReturnsOnCall[len(fake.filterArgsForCall)]
	fake.filterArgsForCall = append(fake.filterArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Filter", []interface{}{arg1})
	fake.filterMutex.Unlock()
	if fake.FilterStub != nil {
		return fake.FilterStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.filterReturns
	return fakeReturns.result1
}

func (fake *BillingOrderService) FilterCallCount() int {
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	return len(fake.filterArgsForCall)
}

func (fake *BillingOrderService) FilterCalls(stub func(string) backend.BillingOrderService) {
	fake.filterMutex.Lock()
	defer fake.filterMutex.Unlock()
	fake.FilterStub = stub
}

func (fake *BillingOrderService) FilterArgsForCall(i int) string {
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	argsForCall := fake.filterArgsForCall[i]
	return argsForCall.arg1
}

func (fake *BillingOrderService) FilterReturns(result1 backend.BillingOrderService) {
	fake.filterMutex.Lock()
	defer fake.filterMutex.Unlock()
	fake.FilterStub = nil
	fake.filterReturns = struct {
		result1 backend.BillingOrderService
	}{result1}
}

func (fake *BillingOrderService) FilterReturnsOnCall(i int, result1 backend.BillingOrderService) {
	fake.filterMutex.Lock()
	defer fake.filterMutex.Unlock()
	fake.FilterStub = nil
	if fake.filterReturnsOnCall == nil {
		fake.filterReturnsOnCall = make(map[int]struct {
			result1 backend.BillingOrderService
		})
	}
	fake.filterReturnsOnCall[i] = struct {
		result1 backend.BillingOrderService
	}{result1}
}

func (fake *BillingOrderService) GetAllObjects() ([]datatypes.Billing_Order, error) {
	fake.getAllObjectsMutex.Lock()
	ret, specificReturn := fake.getAllObjectsReturnsOnCall[len(fake.getAllObjectsArgsForCall)]
	fake.getAllObjectsArgsForCall = append(fake.getAllObjectsArgsForCall, struct {
	}{})
	fake.recordInvocation("GetAllObjects", []interface{}{})
	fake.getAllObjectsMutex.Unlock()
	if fake.GetAllObjectsStub != nil {
		return fake.GetAllObjectsStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getAllObjectsReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *BillingOrderService) GetAllObjectsCallCount() int {
	fake.getAllObjectsMutex.RLock()
	defer fake.getAllObjectsMutex.RUnlock()
	return len(fake.getAllObjectsArgsForCall)
}

func (fake *BillingOrderService) GetAllObjectsCalls(stub func() ([]datatypes.Billing_Order, error)) {
	fake.getAllObjectsMutex.Lock()
	defer fake.getAllObjectsMutex.Unlock()
	fake.GetAllObjectsStub = stub
}

func (fake *BillingOrderService) GetAllObjectsReturns(result1 []datatypes.Billing_Order, result2 error) {
	fake.getAllObjectsMutex.Lock()
	defer fake.getAllObjectsMutex.Unlock()
	fake.GetAllObjectsStub = nil
	fake.getAllObjectsReturns = struct {
		result1 []datatypes.Billing_Order
		result2 error
	}{result1, result2}
}

func (fake *BillingOrderService) GetAllObjectsReturnsOnCall(i int, result1 []datatypes.Billing_Order, result2 error) {
	fake.getAllObjectsMutex.Lock()
	defer fake.getAllObjectsMutex.Unlock()
	fake.GetAllObjectsStub = nil
	if fake.getAllObjectsReturnsOnCall == nil {
		fake.getAllObjectsReturnsOnCall = make(map[int]struct {
			result1 []datatypes.Billing_Order
			result2 error
		})
	}
	fake.getAllObjectsReturnsOnCall[i] = struct {
		result1 []datatypes.Billing_Order
		result2 error
	}{result1, result2}
}

func (fake *BillingOrderService) GetObject() (datatypes.Billing_Order, error) {
	fake.getObjectMutex.Lock()
	ret, specificReturn := fake.getObjectReturnsOnCall[len(fake.getObjectArgsForCall)]
	fake.getObjectArgsForCall = append(fake.getObjectArgsForCall, struct {
	}{})
	fake.recordInvocation("GetObject", []interface{}{})
	fake.getObjectMutex.Unlock()
	if fake.GetObjectStub != nil {
		return fake.GetObjectStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getObjectReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *BillingOrderService) GetObjectCallCount() int {
	fake.getObjectMutex.RLock()
	defer fake.getObjectMutex.RUnlock()
	return len(fake.getObjectArgsForCall)
}

func (fake *BillingOrderService) GetObjectCalls(stub func() (datatypes.Billing_Order, error)) {
	fake.getObjectMutex.Lock()
	defer fake.getObjectMutex.Unlock()
	fake.GetObjectStub = stub
}

func (fake *BillingOrderService) GetObjectReturns(result1 datatypes.Billing_Order, result2 error) {
	fake.getObjectMutex.Lock()
	defer fake.getObjectMutex.Unlock()
	fake.GetObjectStub = nil
	fake.getObjectReturns = struct {
		result1 datatypes.Billing_Order
		result2 error
	}{result1, result2}
}

func (fake *BillingOrderService) GetObjectReturnsOnCall(i int, result1 datatypes.Billing_Order, result2 error) {
	fake.getObjectMutex.Lock()
	defer fake.getObjectMutex.Unlock()
	fake.GetObjectStub = nil
	if fake.getObjectReturnsOnCall == nil {
		fake.getObjectReturnsOnCall = make(map[int]struct {
			result1 datatypes.Billing_Order
			result2 error
		})
	}
	fake.getObjectReturnsOnCall[i] = struct {
		result1 datatypes.Billing_Order
		result2 error
	}{result1, result2}
}

func (fake *BillingOrderService) ID(arg1 int) backend.BillingOrderService {
	fake.iDMutex.Lock()
	ret, specificReturn := fake.iDReturnsOnCall[len(fake.iDArgsForCall)]
	fake.iDArgsForCall = append(fake.iDArgsForCall, struct {
		arg1 int
	}{arg1})
	fake.recordInvocation("ID", []interface{}{arg1})
	fake.iDMutex.Unlock()
	if fake.IDStub != nil {
		return fake.IDStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.iDReturns
	return fakeReturns.result1
}

func (fake *BillingOrderService) IDCallCount() int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	return len(fake.iDArgsForCall)
}

func (fake *BillingOrderService) IDCalls(stub func(int) backend.BillingOrderService) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = stub
}

func (fake *BillingOrderService) IDArgsForCall(i int) int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	argsForCall := fake.iDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *BillingOrderService) IDReturns(result1 backend.BillingOrderService) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	fake.iDReturns = struct {
		result1 backend.BillingOrderService
	}{result1}
}

func (fake *BillingOrderService) IDReturnsOnCall(i int, result1 backend.BillingOrderService) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	if fake.iDReturnsOnCall == nil {
		fake.iDReturnsOnCall = make(map[int]struct {
			result1 backend.BillingOrderService
		})
	}
	fake.iDReturnsOnCall[i] = struct {
		result1 backend.BillingOrderService
	}{result1}
}

func (fake *BillingOrderService) Mask(arg1 string) backend.BillingOrderService {
	fake.maskMutex.Lock()
	ret, specificReturn := fake.maskReturnsOnCall[len(fake.maskArgsForCall)]
	fake.maskArgsForCall = append(fake.maskArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Mask", []interface{}{arg1})
	fake.maskMutex.Unlock()
	if fake.MaskStub != nil {
		return fake.MaskStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.maskReturns
	return fakeReturns.result1
}

func (fake *BillingOrderService) MaskCallCount() int {
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	return len(fake.maskArgsForCall)
}

func (fake *BillingOrderService) MaskCalls(stub func(string) backend.BillingOrderService) {
	fake.maskMutex.Lock()
	defer fake.maskMutex.Unlock()
	fake.MaskStub = stub
}

func (fake *BillingOrderService) MaskArgsForCall(i int) string {
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	argsForCall := fake.maskArgsForCall[i]
	return argsForCall.arg1
}

func (fake *BillingOrderService) MaskReturns(result1 backend.BillingOrderService) {
	fake.maskMutex.Lock()
	defer fake.maskMutex.Unlock()
	fake.MaskStub = nil
	fake.maskReturns = struct {
		result1 backend.BillingOrderService
	}{result1}
}

func (fake *BillingOrderService) MaskReturnsOnCall(i int, result1 backend.BillingOrderService) {
	fake.maskMutex.Lock()
	defer fake.maskMutex.Unlock()
	fake.MaskStub = nil
	if fake.maskReturnsOnCall == nil {
		fake.maskReturnsOnCall = make(map[int]struct {
			result1 backend.BillingOrderService
		})
	}
	fake.maskReturnsOnCall[i] = struct {
		result1 backend.BillingOrderService
	}{result1}
}

func (fake *BillingOrderService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	fake.getAllObjectsMutex.RLock()
	defer fake.getAllObjectsMutex.RUnlock()
	fake.getObjectMutex.RLock()
	defer fake.getObjectMutex.RUnlock()
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *BillingOrderService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ backend.BillingOrderService = new(BillingOrderService)
