// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.ibm.com/alchemy-containers/armada-cluster/iaas/softlayer/backend"
)

type BillingItemService struct {
	FilterStub        func(filter string) backend.BillingItemService
	filterMutex       sync.RWMutex
	filterArgsForCall []struct {
		filter string
	}
	filterReturns struct {
		result1 backend.BillingItemService
	}
	filterReturnsOnCall map[int]struct {
		result1 backend.BillingItemService
	}
	MaskStub        func(string) backend.BillingItemService
	maskMutex       sync.RWMutex
	maskArgsForCall []struct {
		arg1 string
	}
	maskReturns struct {
		result1 backend.BillingItemService
	}
	maskReturnsOnCall map[int]struct {
		result1 backend.BillingItemService
	}
	IDStub        func(int) backend.BillingItemService
	iDMutex       sync.RWMutex
	iDArgsForCall []struct {
		arg1 int
	}
	iDReturns struct {
		result1 backend.BillingItemService
	}
	iDReturnsOnCall map[int]struct {
		result1 backend.BillingItemService
	}
	CancelItemStub        func(cancelImmediately *bool, cancelAssociatedBillingItems *bool, reason *string, customerNote *string) (resp bool, err error)
	cancelItemMutex       sync.RWMutex
	cancelItemArgsForCall []struct {
		cancelImmediately            *bool
		cancelAssociatedBillingItems *bool
		reason                       *string
		customerNote                 *string
	}
	cancelItemReturns struct {
		result1 bool
		result2 error
	}
	cancelItemReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *BillingItemService) Filter(filter string) backend.BillingItemService {
	fake.filterMutex.Lock()
	ret, specificReturn := fake.filterReturnsOnCall[len(fake.filterArgsForCall)]
	fake.filterArgsForCall = append(fake.filterArgsForCall, struct {
		filter string
	}{filter})
	fake.recordInvocation("Filter", []interface{}{filter})
	fake.filterMutex.Unlock()
	if fake.FilterStub != nil {
		return fake.FilterStub(filter)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.filterReturns.result1
}

func (fake *BillingItemService) FilterCallCount() int {
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	return len(fake.filterArgsForCall)
}

func (fake *BillingItemService) FilterArgsForCall(i int) string {
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	return fake.filterArgsForCall[i].filter
}

func (fake *BillingItemService) FilterReturns(result1 backend.BillingItemService) {
	fake.FilterStub = nil
	fake.filterReturns = struct {
		result1 backend.BillingItemService
	}{result1}
}

func (fake *BillingItemService) FilterReturnsOnCall(i int, result1 backend.BillingItemService) {
	fake.FilterStub = nil
	if fake.filterReturnsOnCall == nil {
		fake.filterReturnsOnCall = make(map[int]struct {
			result1 backend.BillingItemService
		})
	}
	fake.filterReturnsOnCall[i] = struct {
		result1 backend.BillingItemService
	}{result1}
}

func (fake *BillingItemService) Mask(arg1 string) backend.BillingItemService {
	fake.maskMutex.Lock()
	ret, specificReturn := fake.maskReturnsOnCall[len(fake.maskArgsForCall)]
	fake.maskArgsForCall = append(fake.maskArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Mask", []interface{}{arg1})
	fake.maskMutex.Unlock()
	if fake.MaskStub != nil {
		return fake.MaskStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.maskReturns.result1
}

func (fake *BillingItemService) MaskCallCount() int {
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	return len(fake.maskArgsForCall)
}

func (fake *BillingItemService) MaskArgsForCall(i int) string {
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	return fake.maskArgsForCall[i].arg1
}

func (fake *BillingItemService) MaskReturns(result1 backend.BillingItemService) {
	fake.MaskStub = nil
	fake.maskReturns = struct {
		result1 backend.BillingItemService
	}{result1}
}

func (fake *BillingItemService) MaskReturnsOnCall(i int, result1 backend.BillingItemService) {
	fake.MaskStub = nil
	if fake.maskReturnsOnCall == nil {
		fake.maskReturnsOnCall = make(map[int]struct {
			result1 backend.BillingItemService
		})
	}
	fake.maskReturnsOnCall[i] = struct {
		result1 backend.BillingItemService
	}{result1}
}

func (fake *BillingItemService) ID(arg1 int) backend.BillingItemService {
	fake.iDMutex.Lock()
	ret, specificReturn := fake.iDReturnsOnCall[len(fake.iDArgsForCall)]
	fake.iDArgsForCall = append(fake.iDArgsForCall, struct {
		arg1 int
	}{arg1})
	fake.recordInvocation("ID", []interface{}{arg1})
	fake.iDMutex.Unlock()
	if fake.IDStub != nil {
		return fake.IDStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.iDReturns.result1
}

func (fake *BillingItemService) IDCallCount() int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	return len(fake.iDArgsForCall)
}

func (fake *BillingItemService) IDArgsForCall(i int) int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	return fake.iDArgsForCall[i].arg1
}

func (fake *BillingItemService) IDReturns(result1 backend.BillingItemService) {
	fake.IDStub = nil
	fake.iDReturns = struct {
		result1 backend.BillingItemService
	}{result1}
}

func (fake *BillingItemService) IDReturnsOnCall(i int, result1 backend.BillingItemService) {
	fake.IDStub = nil
	if fake.iDReturnsOnCall == nil {
		fake.iDReturnsOnCall = make(map[int]struct {
			result1 backend.BillingItemService
		})
	}
	fake.iDReturnsOnCall[i] = struct {
		result1 backend.BillingItemService
	}{result1}
}

func (fake *BillingItemService) CancelItem(cancelImmediately *bool, cancelAssociatedBillingItems *bool, reason *string, customerNote *string) (resp bool, err error) {
	fake.cancelItemMutex.Lock()
	ret, specificReturn := fake.cancelItemReturnsOnCall[len(fake.cancelItemArgsForCall)]
	fake.cancelItemArgsForCall = append(fake.cancelItemArgsForCall, struct {
		cancelImmediately            *bool
		cancelAssociatedBillingItems *bool
		reason                       *string
		customerNote                 *string
	}{cancelImmediately, cancelAssociatedBillingItems, reason, customerNote})
	fake.recordInvocation("CancelItem", []interface{}{cancelImmediately, cancelAssociatedBillingItems, reason, customerNote})
	fake.cancelItemMutex.Unlock()
	if fake.CancelItemStub != nil {
		return fake.CancelItemStub(cancelImmediately, cancelAssociatedBillingItems, reason, customerNote)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.cancelItemReturns.result1, fake.cancelItemReturns.result2
}

func (fake *BillingItemService) CancelItemCallCount() int {
	fake.cancelItemMutex.RLock()
	defer fake.cancelItemMutex.RUnlock()
	return len(fake.cancelItemArgsForCall)
}

func (fake *BillingItemService) CancelItemArgsForCall(i int) (*bool, *bool, *string, *string) {
	fake.cancelItemMutex.RLock()
	defer fake.cancelItemMutex.RUnlock()
	return fake.cancelItemArgsForCall[i].cancelImmediately, fake.cancelItemArgsForCall[i].cancelAssociatedBillingItems, fake.cancelItemArgsForCall[i].reason, fake.cancelItemArgsForCall[i].customerNote
}

func (fake *BillingItemService) CancelItemReturns(result1 bool, result2 error) {
	fake.CancelItemStub = nil
	fake.cancelItemReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *BillingItemService) CancelItemReturnsOnCall(i int, result1 bool, result2 error) {
	fake.CancelItemStub = nil
	if fake.cancelItemReturnsOnCall == nil {
		fake.cancelItemReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.cancelItemReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *BillingItemService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	fake.cancelItemMutex.RLock()
	defer fake.cancelItemMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *BillingItemService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ backend.BillingItemService = new(BillingItemService)
