// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	sync "sync"

	backend "github.com/IBM/ibmcloud-storage-volume-lib/volume-providers/softlayer/backend"
)

type BillingItemService struct {
	CancelItemStub        func(*bool, *bool, *string, *string) (bool, error)
	cancelItemMutex       sync.RWMutex
	cancelItemArgsForCall []struct {
		arg1 *bool
		arg2 *bool
		arg3 *string
		arg4 *string
	}
	cancelItemReturns struct {
		result1 bool
		result2 error
	}
	cancelItemReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	CancelServiceStub        func() (bool, error)
	cancelServiceMutex       sync.RWMutex
	cancelServiceArgsForCall []struct {
	}
	cancelServiceReturns struct {
		result1 bool
		result2 error
	}
	cancelServiceReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	FilterStub        func(string) backend.BillingItemService
	filterMutex       sync.RWMutex
	filterArgsForCall []struct {
		arg1 string
	}
	filterReturns struct {
		result1 backend.BillingItemService
	}
	filterReturnsOnCall map[int]struct {
		result1 backend.BillingItemService
	}
	IDStub        func(int) backend.BillingItemService
	iDMutex       sync.RWMutex
	iDArgsForCall []struct {
		arg1 int
	}
	iDReturns struct {
		result1 backend.BillingItemService
	}
	iDReturnsOnCall map[int]struct {
		result1 backend.BillingItemService
	}
	MaskStub        func(string) backend.BillingItemService
	maskMutex       sync.RWMutex
	maskArgsForCall []struct {
		arg1 string
	}
	maskReturns struct {
		result1 backend.BillingItemService
	}
	maskReturnsOnCall map[int]struct {
		result1 backend.BillingItemService
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *BillingItemService) CancelItem(arg1 *bool, arg2 *bool, arg3 *string, arg4 *string) (bool, error) {
	fake.cancelItemMutex.Lock()
	ret, specificReturn := fake.cancelItemReturnsOnCall[len(fake.cancelItemArgsForCall)]
	fake.cancelItemArgsForCall = append(fake.cancelItemArgsForCall, struct {
		arg1 *bool
		arg2 *bool
		arg3 *string
		arg4 *string
	}{arg1, arg2, arg3, arg4})
	fake.recordInvocation("CancelItem", []interface{}{arg1, arg2, arg3, arg4})
	fake.cancelItemMutex.Unlock()
	if fake.CancelItemStub != nil {
		return fake.CancelItemStub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.cancelItemReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *BillingItemService) CancelItemCallCount() int {
	fake.cancelItemMutex.RLock()
	defer fake.cancelItemMutex.RUnlock()
	return len(fake.cancelItemArgsForCall)
}

func (fake *BillingItemService) CancelItemCalls(stub func(*bool, *bool, *string, *string) (bool, error)) {
	fake.cancelItemMutex.Lock()
	defer fake.cancelItemMutex.Unlock()
	fake.CancelItemStub = stub
}

func (fake *BillingItemService) CancelItemArgsForCall(i int) (*bool, *bool, *string, *string) {
	fake.cancelItemMutex.RLock()
	defer fake.cancelItemMutex.RUnlock()
	argsForCall := fake.cancelItemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *BillingItemService) CancelItemReturns(result1 bool, result2 error) {
	fake.cancelItemMutex.Lock()
	defer fake.cancelItemMutex.Unlock()
	fake.CancelItemStub = nil
	fake.cancelItemReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *BillingItemService) CancelItemReturnsOnCall(i int, result1 bool, result2 error) {
	fake.cancelItemMutex.Lock()
	defer fake.cancelItemMutex.Unlock()
	fake.CancelItemStub = nil
	if fake.cancelItemReturnsOnCall == nil {
		fake.cancelItemReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.cancelItemReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *BillingItemService) CancelService() (bool, error) {
	fake.cancelServiceMutex.Lock()
	ret, specificReturn := fake.cancelServiceReturnsOnCall[len(fake.cancelServiceArgsForCall)]
	fake.cancelServiceArgsForCall = append(fake.cancelServiceArgsForCall, struct {
	}{})
	fake.recordInvocation("CancelService", []interface{}{})
	fake.cancelServiceMutex.Unlock()
	if fake.CancelServiceStub != nil {
		return fake.CancelServiceStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.cancelServiceReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *BillingItemService) CancelServiceCallCount() int {
	fake.cancelServiceMutex.RLock()
	defer fake.cancelServiceMutex.RUnlock()
	return len(fake.cancelServiceArgsForCall)
}

func (fake *BillingItemService) CancelServiceCalls(stub func() (bool, error)) {
	fake.cancelServiceMutex.Lock()
	defer fake.cancelServiceMutex.Unlock()
	fake.CancelServiceStub = stub
}

func (fake *BillingItemService) CancelServiceReturns(result1 bool, result2 error) {
	fake.cancelServiceMutex.Lock()
	defer fake.cancelServiceMutex.Unlock()
	fake.CancelServiceStub = nil
	fake.cancelServiceReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *BillingItemService) CancelServiceReturnsOnCall(i int, result1 bool, result2 error) {
	fake.cancelServiceMutex.Lock()
	defer fake.cancelServiceMutex.Unlock()
	fake.CancelServiceStub = nil
	if fake.cancelServiceReturnsOnCall == nil {
		fake.cancelServiceReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.cancelServiceReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *BillingItemService) Filter(arg1 string) backend.BillingItemService {
	fake.filterMutex.Lock()
	ret, specificReturn := fake.filterReturnsOnCall[len(fake.filterArgsForCall)]
	fake.filterArgsForCall = append(fake.filterArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Filter", []interface{}{arg1})
	fake.filterMutex.Unlock()
	if fake.FilterStub != nil {
		return fake.FilterStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.filterReturns
	return fakeReturns.result1
}

func (fake *BillingItemService) FilterCallCount() int {
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	return len(fake.filterArgsForCall)
}

func (fake *BillingItemService) FilterCalls(stub func(string) backend.BillingItemService) {
	fake.filterMutex.Lock()
	defer fake.filterMutex.Unlock()
	fake.FilterStub = stub
}

func (fake *BillingItemService) FilterArgsForCall(i int) string {
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	argsForCall := fake.filterArgsForCall[i]
	return argsForCall.arg1
}

func (fake *BillingItemService) FilterReturns(result1 backend.BillingItemService) {
	fake.filterMutex.Lock()
	defer fake.filterMutex.Unlock()
	fake.FilterStub = nil
	fake.filterReturns = struct {
		result1 backend.BillingItemService
	}{result1}
}

func (fake *BillingItemService) FilterReturnsOnCall(i int, result1 backend.BillingItemService) {
	fake.filterMutex.Lock()
	defer fake.filterMutex.Unlock()
	fake.FilterStub = nil
	if fake.filterReturnsOnCall == nil {
		fake.filterReturnsOnCall = make(map[int]struct {
			result1 backend.BillingItemService
		})
	}
	fake.filterReturnsOnCall[i] = struct {
		result1 backend.BillingItemService
	}{result1}
}

func (fake *BillingItemService) ID(arg1 int) backend.BillingItemService {
	fake.iDMutex.Lock()
	ret, specificReturn := fake.iDReturnsOnCall[len(fake.iDArgsForCall)]
	fake.iDArgsForCall = append(fake.iDArgsForCall, struct {
		arg1 int
	}{arg1})
	fake.recordInvocation("ID", []interface{}{arg1})
	fake.iDMutex.Unlock()
	if fake.IDStub != nil {
		return fake.IDStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.iDReturns
	return fakeReturns.result1
}

func (fake *BillingItemService) IDCallCount() int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	return len(fake.iDArgsForCall)
}

func (fake *BillingItemService) IDCalls(stub func(int) backend.BillingItemService) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = stub
}

func (fake *BillingItemService) IDArgsForCall(i int) int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	argsForCall := fake.iDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *BillingItemService) IDReturns(result1 backend.BillingItemService) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	fake.iDReturns = struct {
		result1 backend.BillingItemService
	}{result1}
}

func (fake *BillingItemService) IDReturnsOnCall(i int, result1 backend.BillingItemService) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	if fake.iDReturnsOnCall == nil {
		fake.iDReturnsOnCall = make(map[int]struct {
			result1 backend.BillingItemService
		})
	}
	fake.iDReturnsOnCall[i] = struct {
		result1 backend.BillingItemService
	}{result1}
}

func (fake *BillingItemService) Mask(arg1 string) backend.BillingItemService {
	fake.maskMutex.Lock()
	ret, specificReturn := fake.maskReturnsOnCall[len(fake.maskArgsForCall)]
	fake.maskArgsForCall = append(fake.maskArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Mask", []interface{}{arg1})
	fake.maskMutex.Unlock()
	if fake.MaskStub != nil {
		return fake.MaskStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.maskReturns
	return fakeReturns.result1
}

func (fake *BillingItemService) MaskCallCount() int {
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	return len(fake.maskArgsForCall)
}

func (fake *BillingItemService) MaskCalls(stub func(string) backend.BillingItemService) {
	fake.maskMutex.Lock()
	defer fake.maskMutex.Unlock()
	fake.MaskStub = stub
}

func (fake *BillingItemService) MaskArgsForCall(i int) string {
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	argsForCall := fake.maskArgsForCall[i]
	return argsForCall.arg1
}

func (fake *BillingItemService) MaskReturns(result1 backend.BillingItemService) {
	fake.maskMutex.Lock()
	defer fake.maskMutex.Unlock()
	fake.MaskStub = nil
	fake.maskReturns = struct {
		result1 backend.BillingItemService
	}{result1}
}

func (fake *BillingItemService) MaskReturnsOnCall(i int, result1 backend.BillingItemService) {
	fake.maskMutex.Lock()
	defer fake.maskMutex.Unlock()
	fake.MaskStub = nil
	if fake.maskReturnsOnCall == nil {
		fake.maskReturnsOnCall = make(map[int]struct {
			result1 backend.BillingItemService
		})
	}
	fake.maskReturnsOnCall[i] = struct {
		result1 backend.BillingItemService
	}{result1}
}

func (fake *BillingItemService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.cancelItemMutex.RLock()
	defer fake.cancelItemMutex.RUnlock()
	fake.cancelServiceMutex.RLock()
	defer fake.cancelServiceMutex.RUnlock()
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *BillingItemService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ backend.BillingItemService = new(BillingItemService)
