// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	sync "sync"

	backend "github.com/IBM/ibmcloud-storage-volume-lib/volume-providers/softlayer/backend"
	datatypes "github.com/softlayer/softlayer-go/datatypes"
)

type LocationService struct {
	FilterStub        func(string) backend.LocationService
	filterMutex       sync.RWMutex
	filterArgsForCall []struct {
		arg1 string
	}
	filterReturns struct {
		result1 backend.LocationService
	}
	filterReturnsOnCall map[int]struct {
		result1 backend.LocationService
	}
	GetDatacentersStub        func() ([]datatypes.Location, error)
	getDatacentersMutex       sync.RWMutex
	getDatacentersArgsForCall []struct {
	}
	getDatacentersReturns struct {
		result1 []datatypes.Location
		result2 error
	}
	getDatacentersReturnsOnCall map[int]struct {
		result1 []datatypes.Location
		result2 error
	}
	IDStub        func(int) backend.LocationService
	iDMutex       sync.RWMutex
	iDArgsForCall []struct {
		arg1 int
	}
	iDReturns struct {
		result1 backend.LocationService
	}
	iDReturnsOnCall map[int]struct {
		result1 backend.LocationService
	}
	MaskStub        func(string) backend.LocationService
	maskMutex       sync.RWMutex
	maskArgsForCall []struct {
		arg1 string
	}
	maskReturns struct {
		result1 backend.LocationService
	}
	maskReturnsOnCall map[int]struct {
		result1 backend.LocationService
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *LocationService) Filter(arg1 string) backend.LocationService {
	fake.filterMutex.Lock()
	ret, specificReturn := fake.filterReturnsOnCall[len(fake.filterArgsForCall)]
	fake.filterArgsForCall = append(fake.filterArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Filter", []interface{}{arg1})
	fake.filterMutex.Unlock()
	if fake.FilterStub != nil {
		return fake.FilterStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.filterReturns
	return fakeReturns.result1
}

func (fake *LocationService) FilterCallCount() int {
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	return len(fake.filterArgsForCall)
}

func (fake *LocationService) FilterCalls(stub func(string) backend.LocationService) {
	fake.filterMutex.Lock()
	defer fake.filterMutex.Unlock()
	fake.FilterStub = stub
}

func (fake *LocationService) FilterArgsForCall(i int) string {
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	argsForCall := fake.filterArgsForCall[i]
	return argsForCall.arg1
}

func (fake *LocationService) FilterReturns(result1 backend.LocationService) {
	fake.filterMutex.Lock()
	defer fake.filterMutex.Unlock()
	fake.FilterStub = nil
	fake.filterReturns = struct {
		result1 backend.LocationService
	}{result1}
}

func (fake *LocationService) FilterReturnsOnCall(i int, result1 backend.LocationService) {
	fake.filterMutex.Lock()
	defer fake.filterMutex.Unlock()
	fake.FilterStub = nil
	if fake.filterReturnsOnCall == nil {
		fake.filterReturnsOnCall = make(map[int]struct {
			result1 backend.LocationService
		})
	}
	fake.filterReturnsOnCall[i] = struct {
		result1 backend.LocationService
	}{result1}
}

func (fake *LocationService) GetDatacenters() ([]datatypes.Location, error) {
	fake.getDatacentersMutex.Lock()
	ret, specificReturn := fake.getDatacentersReturnsOnCall[len(fake.getDatacentersArgsForCall)]
	fake.getDatacentersArgsForCall = append(fake.getDatacentersArgsForCall, struct {
	}{})
	fake.recordInvocation("GetDatacenters", []interface{}{})
	fake.getDatacentersMutex.Unlock()
	if fake.GetDatacentersStub != nil {
		return fake.GetDatacentersStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getDatacentersReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *LocationService) GetDatacentersCallCount() int {
	fake.getDatacentersMutex.RLock()
	defer fake.getDatacentersMutex.RUnlock()
	return len(fake.getDatacentersArgsForCall)
}

func (fake *LocationService) GetDatacentersCalls(stub func() ([]datatypes.Location, error)) {
	fake.getDatacentersMutex.Lock()
	defer fake.getDatacentersMutex.Unlock()
	fake.GetDatacentersStub = stub
}

func (fake *LocationService) GetDatacentersReturns(result1 []datatypes.Location, result2 error) {
	fake.getDatacentersMutex.Lock()
	defer fake.getDatacentersMutex.Unlock()
	fake.GetDatacentersStub = nil
	fake.getDatacentersReturns = struct {
		result1 []datatypes.Location
		result2 error
	}{result1, result2}
}

func (fake *LocationService) GetDatacentersReturnsOnCall(i int, result1 []datatypes.Location, result2 error) {
	fake.getDatacentersMutex.Lock()
	defer fake.getDatacentersMutex.Unlock()
	fake.GetDatacentersStub = nil
	if fake.getDatacentersReturnsOnCall == nil {
		fake.getDatacentersReturnsOnCall = make(map[int]struct {
			result1 []datatypes.Location
			result2 error
		})
	}
	fake.getDatacentersReturnsOnCall[i] = struct {
		result1 []datatypes.Location
		result2 error
	}{result1, result2}
}

func (fake *LocationService) ID(arg1 int) backend.LocationService {
	fake.iDMutex.Lock()
	ret, specificReturn := fake.iDReturnsOnCall[len(fake.iDArgsForCall)]
	fake.iDArgsForCall = append(fake.iDArgsForCall, struct {
		arg1 int
	}{arg1})
	fake.recordInvocation("ID", []interface{}{arg1})
	fake.iDMutex.Unlock()
	if fake.IDStub != nil {
		return fake.IDStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.iDReturns
	return fakeReturns.result1
}

func (fake *LocationService) IDCallCount() int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	return len(fake.iDArgsForCall)
}

func (fake *LocationService) IDCalls(stub func(int) backend.LocationService) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = stub
}

func (fake *LocationService) IDArgsForCall(i int) int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	argsForCall := fake.iDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *LocationService) IDReturns(result1 backend.LocationService) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	fake.iDReturns = struct {
		result1 backend.LocationService
	}{result1}
}

func (fake *LocationService) IDReturnsOnCall(i int, result1 backend.LocationService) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	if fake.iDReturnsOnCall == nil {
		fake.iDReturnsOnCall = make(map[int]struct {
			result1 backend.LocationService
		})
	}
	fake.iDReturnsOnCall[i] = struct {
		result1 backend.LocationService
	}{result1}
}

func (fake *LocationService) Mask(arg1 string) backend.LocationService {
	fake.maskMutex.Lock()
	ret, specificReturn := fake.maskReturnsOnCall[len(fake.maskArgsForCall)]
	fake.maskArgsForCall = append(fake.maskArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Mask", []interface{}{arg1})
	fake.maskMutex.Unlock()
	if fake.MaskStub != nil {
		return fake.MaskStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.maskReturns
	return fakeReturns.result1
}

func (fake *LocationService) MaskCallCount() int {
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	return len(fake.maskArgsForCall)
}

func (fake *LocationService) MaskCalls(stub func(string) backend.LocationService) {
	fake.maskMutex.Lock()
	defer fake.maskMutex.Unlock()
	fake.MaskStub = stub
}

func (fake *LocationService) MaskArgsForCall(i int) string {
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	argsForCall := fake.maskArgsForCall[i]
	return argsForCall.arg1
}

func (fake *LocationService) MaskReturns(result1 backend.LocationService) {
	fake.maskMutex.Lock()
	defer fake.maskMutex.Unlock()
	fake.MaskStub = nil
	fake.maskReturns = struct {
		result1 backend.LocationService
	}{result1}
}

func (fake *LocationService) MaskReturnsOnCall(i int, result1 backend.LocationService) {
	fake.maskMutex.Lock()
	defer fake.maskMutex.Unlock()
	fake.MaskStub = nil
	if fake.maskReturnsOnCall == nil {
		fake.maskReturnsOnCall = make(map[int]struct {
			result1 backend.LocationService
		})
	}
	fake.maskReturnsOnCall[i] = struct {
		result1 backend.LocationService
	}{result1}
}

func (fake *LocationService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	fake.getDatacentersMutex.RLock()
	defer fake.getDatacentersMutex.RUnlock()
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *LocationService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ backend.LocationService = new(LocationService)
