// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	sync "sync"

	backend "github.com/IBM/ibmcloud-storage-volume-lib/volume-providers/softlayer/backend"
	datatypes "github.com/softlayer/softlayer-go/datatypes"
)

type NetworkSubnetIpAddressService struct {
	FilterStub        func(string) backend.NetworkSubnetIpAddressService
	filterMutex       sync.RWMutex
	filterArgsForCall []struct {
		arg1 string
	}
	filterReturns struct {
		result1 backend.NetworkSubnetIpAddressService
	}
	filterReturnsOnCall map[int]struct {
		result1 backend.NetworkSubnetIpAddressService
	}
	GetByIPAddressStub        func(*string) (datatypes.Network_Subnet_IpAddress, error)
	getByIPAddressMutex       sync.RWMutex
	getByIPAddressArgsForCall []struct {
		arg1 *string
	}
	getByIPAddressReturns struct {
		result1 datatypes.Network_Subnet_IpAddress
		result2 error
	}
	getByIPAddressReturnsOnCall map[int]struct {
		result1 datatypes.Network_Subnet_IpAddress
		result2 error
	}
	GetObjectStub        func() (datatypes.Network_Subnet_IpAddress, error)
	getObjectMutex       sync.RWMutex
	getObjectArgsForCall []struct {
	}
	getObjectReturns struct {
		result1 datatypes.Network_Subnet_IpAddress
		result2 error
	}
	getObjectReturnsOnCall map[int]struct {
		result1 datatypes.Network_Subnet_IpAddress
		result2 error
	}
	IDStub        func(int) backend.NetworkSubnetIpAddressService
	iDMutex       sync.RWMutex
	iDArgsForCall []struct {
		arg1 int
	}
	iDReturns struct {
		result1 backend.NetworkSubnetIpAddressService
	}
	iDReturnsOnCall map[int]struct {
		result1 backend.NetworkSubnetIpAddressService
	}
	MaskStub        func(string) backend.NetworkSubnetIpAddressService
	maskMutex       sync.RWMutex
	maskArgsForCall []struct {
		arg1 string
	}
	maskReturns struct {
		result1 backend.NetworkSubnetIpAddressService
	}
	maskReturnsOnCall map[int]struct {
		result1 backend.NetworkSubnetIpAddressService
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *NetworkSubnetIpAddressService) Filter(arg1 string) backend.NetworkSubnetIpAddressService {
	fake.filterMutex.Lock()
	ret, specificReturn := fake.filterReturnsOnCall[len(fake.filterArgsForCall)]
	fake.filterArgsForCall = append(fake.filterArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Filter", []interface{}{arg1})
	fake.filterMutex.Unlock()
	if fake.FilterStub != nil {
		return fake.FilterStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.filterReturns
	return fakeReturns.result1
}

func (fake *NetworkSubnetIpAddressService) FilterCallCount() int {
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	return len(fake.filterArgsForCall)
}

func (fake *NetworkSubnetIpAddressService) FilterCalls(stub func(string) backend.NetworkSubnetIpAddressService) {
	fake.filterMutex.Lock()
	defer fake.filterMutex.Unlock()
	fake.FilterStub = stub
}

func (fake *NetworkSubnetIpAddressService) FilterArgsForCall(i int) string {
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	argsForCall := fake.filterArgsForCall[i]
	return argsForCall.arg1
}

func (fake *NetworkSubnetIpAddressService) FilterReturns(result1 backend.NetworkSubnetIpAddressService) {
	fake.filterMutex.Lock()
	defer fake.filterMutex.Unlock()
	fake.FilterStub = nil
	fake.filterReturns = struct {
		result1 backend.NetworkSubnetIpAddressService
	}{result1}
}

func (fake *NetworkSubnetIpAddressService) FilterReturnsOnCall(i int, result1 backend.NetworkSubnetIpAddressService) {
	fake.filterMutex.Lock()
	defer fake.filterMutex.Unlock()
	fake.FilterStub = nil
	if fake.filterReturnsOnCall == nil {
		fake.filterReturnsOnCall = make(map[int]struct {
			result1 backend.NetworkSubnetIpAddressService
		})
	}
	fake.filterReturnsOnCall[i] = struct {
		result1 backend.NetworkSubnetIpAddressService
	}{result1}
}

func (fake *NetworkSubnetIpAddressService) GetByIPAddress(arg1 *string) (datatypes.Network_Subnet_IpAddress, error) {
	fake.getByIPAddressMutex.Lock()
	ret, specificReturn := fake.getByIPAddressReturnsOnCall[len(fake.getByIPAddressArgsForCall)]
	fake.getByIPAddressArgsForCall = append(fake.getByIPAddressArgsForCall, struct {
		arg1 *string
	}{arg1})
	fake.recordInvocation("GetByIPAddress", []interface{}{arg1})
	fake.getByIPAddressMutex.Unlock()
	if fake.GetByIPAddressStub != nil {
		return fake.GetByIPAddressStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getByIPAddressReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *NetworkSubnetIpAddressService) GetByIPAddressCallCount() int {
	fake.getByIPAddressMutex.RLock()
	defer fake.getByIPAddressMutex.RUnlock()
	return len(fake.getByIPAddressArgsForCall)
}

func (fake *NetworkSubnetIpAddressService) GetByIPAddressCalls(stub func(*string) (datatypes.Network_Subnet_IpAddress, error)) {
	fake.getByIPAddressMutex.Lock()
	defer fake.getByIPAddressMutex.Unlock()
	fake.GetByIPAddressStub = stub
}

func (fake *NetworkSubnetIpAddressService) GetByIPAddressArgsForCall(i int) *string {
	fake.getByIPAddressMutex.RLock()
	defer fake.getByIPAddressMutex.RUnlock()
	argsForCall := fake.getByIPAddressArgsForCall[i]
	return argsForCall.arg1
}

func (fake *NetworkSubnetIpAddressService) GetByIPAddressReturns(result1 datatypes.Network_Subnet_IpAddress, result2 error) {
	fake.getByIPAddressMutex.Lock()
	defer fake.getByIPAddressMutex.Unlock()
	fake.GetByIPAddressStub = nil
	fake.getByIPAddressReturns = struct {
		result1 datatypes.Network_Subnet_IpAddress
		result2 error
	}{result1, result2}
}

func (fake *NetworkSubnetIpAddressService) GetByIPAddressReturnsOnCall(i int, result1 datatypes.Network_Subnet_IpAddress, result2 error) {
	fake.getByIPAddressMutex.Lock()
	defer fake.getByIPAddressMutex.Unlock()
	fake.GetByIPAddressStub = nil
	if fake.getByIPAddressReturnsOnCall == nil {
		fake.getByIPAddressReturnsOnCall = make(map[int]struct {
			result1 datatypes.Network_Subnet_IpAddress
			result2 error
		})
	}
	fake.getByIPAddressReturnsOnCall[i] = struct {
		result1 datatypes.Network_Subnet_IpAddress
		result2 error
	}{result1, result2}
}

func (fake *NetworkSubnetIpAddressService) GetObject() (datatypes.Network_Subnet_IpAddress, error) {
	fake.getObjectMutex.Lock()
	ret, specificReturn := fake.getObjectReturnsOnCall[len(fake.getObjectArgsForCall)]
	fake.getObjectArgsForCall = append(fake.getObjectArgsForCall, struct {
	}{})
	fake.recordInvocation("GetObject", []interface{}{})
	fake.getObjectMutex.Unlock()
	if fake.GetObjectStub != nil {
		return fake.GetObjectStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getObjectReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *NetworkSubnetIpAddressService) GetObjectCallCount() int {
	fake.getObjectMutex.RLock()
	defer fake.getObjectMutex.RUnlock()
	return len(fake.getObjectArgsForCall)
}

func (fake *NetworkSubnetIpAddressService) GetObjectCalls(stub func() (datatypes.Network_Subnet_IpAddress, error)) {
	fake.getObjectMutex.Lock()
	defer fake.getObjectMutex.Unlock()
	fake.GetObjectStub = stub
}

func (fake *NetworkSubnetIpAddressService) GetObjectReturns(result1 datatypes.Network_Subnet_IpAddress, result2 error) {
	fake.getObjectMutex.Lock()
	defer fake.getObjectMutex.Unlock()
	fake.GetObjectStub = nil
	fake.getObjectReturns = struct {
		result1 datatypes.Network_Subnet_IpAddress
		result2 error
	}{result1, result2}
}

func (fake *NetworkSubnetIpAddressService) GetObjectReturnsOnCall(i int, result1 datatypes.Network_Subnet_IpAddress, result2 error) {
	fake.getObjectMutex.Lock()
	defer fake.getObjectMutex.Unlock()
	fake.GetObjectStub = nil
	if fake.getObjectReturnsOnCall == nil {
		fake.getObjectReturnsOnCall = make(map[int]struct {
			result1 datatypes.Network_Subnet_IpAddress
			result2 error
		})
	}
	fake.getObjectReturnsOnCall[i] = struct {
		result1 datatypes.Network_Subnet_IpAddress
		result2 error
	}{result1, result2}
}

func (fake *NetworkSubnetIpAddressService) ID(arg1 int) backend.NetworkSubnetIpAddressService {
	fake.iDMutex.Lock()
	ret, specificReturn := fake.iDReturnsOnCall[len(fake.iDArgsForCall)]
	fake.iDArgsForCall = append(fake.iDArgsForCall, struct {
		arg1 int
	}{arg1})
	fake.recordInvocation("ID", []interface{}{arg1})
	fake.iDMutex.Unlock()
	if fake.IDStub != nil {
		return fake.IDStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.iDReturns
	return fakeReturns.result1
}

func (fake *NetworkSubnetIpAddressService) IDCallCount() int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	return len(fake.iDArgsForCall)
}

func (fake *NetworkSubnetIpAddressService) IDCalls(stub func(int) backend.NetworkSubnetIpAddressService) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = stub
}

func (fake *NetworkSubnetIpAddressService) IDArgsForCall(i int) int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	argsForCall := fake.iDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *NetworkSubnetIpAddressService) IDReturns(result1 backend.NetworkSubnetIpAddressService) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	fake.iDReturns = struct {
		result1 backend.NetworkSubnetIpAddressService
	}{result1}
}

func (fake *NetworkSubnetIpAddressService) IDReturnsOnCall(i int, result1 backend.NetworkSubnetIpAddressService) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	if fake.iDReturnsOnCall == nil {
		fake.iDReturnsOnCall = make(map[int]struct {
			result1 backend.NetworkSubnetIpAddressService
		})
	}
	fake.iDReturnsOnCall[i] = struct {
		result1 backend.NetworkSubnetIpAddressService
	}{result1}
}

func (fake *NetworkSubnetIpAddressService) Mask(arg1 string) backend.NetworkSubnetIpAddressService {
	fake.maskMutex.Lock()
	ret, specificReturn := fake.maskReturnsOnCall[len(fake.maskArgsForCall)]
	fake.maskArgsForCall = append(fake.maskArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Mask", []interface{}{arg1})
	fake.maskMutex.Unlock()
	if fake.MaskStub != nil {
		return fake.MaskStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.maskReturns
	return fakeReturns.result1
}

func (fake *NetworkSubnetIpAddressService) MaskCallCount() int {
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	return len(fake.maskArgsForCall)
}

func (fake *NetworkSubnetIpAddressService) MaskCalls(stub func(string) backend.NetworkSubnetIpAddressService) {
	fake.maskMutex.Lock()
	defer fake.maskMutex.Unlock()
	fake.MaskStub = stub
}

func (fake *NetworkSubnetIpAddressService) MaskArgsForCall(i int) string {
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	argsForCall := fake.maskArgsForCall[i]
	return argsForCall.arg1
}

func (fake *NetworkSubnetIpAddressService) MaskReturns(result1 backend.NetworkSubnetIpAddressService) {
	fake.maskMutex.Lock()
	defer fake.maskMutex.Unlock()
	fake.MaskStub = nil
	fake.maskReturns = struct {
		result1 backend.NetworkSubnetIpAddressService
	}{result1}
}

func (fake *NetworkSubnetIpAddressService) MaskReturnsOnCall(i int, result1 backend.NetworkSubnetIpAddressService) {
	fake.maskMutex.Lock()
	defer fake.maskMutex.Unlock()
	fake.MaskStub = nil
	if fake.maskReturnsOnCall == nil {
		fake.maskReturnsOnCall = make(map[int]struct {
			result1 backend.NetworkSubnetIpAddressService
		})
	}
	fake.maskReturnsOnCall[i] = struct {
		result1 backend.NetworkSubnetIpAddressService
	}{result1}
}

func (fake *NetworkSubnetIpAddressService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	fake.getByIPAddressMutex.RLock()
	defer fake.getByIPAddressMutex.RUnlock()
	fake.getObjectMutex.RLock()
	defer fake.getObjectMutex.RUnlock()
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *NetworkSubnetIpAddressService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ backend.NetworkSubnetIpAddressService = new(NetworkSubnetIpAddressService)
