// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	sync "sync"

	backend "github.com/IBM/ibmcloud-storage-volume-lib/volume-providers/softlayer/backend"
	datatypes "github.com/softlayer/softlayer-go/datatypes"
)

type ProductOrderService struct {
	FilterStub        func(string) backend.ProductOrderService
	filterMutex       sync.RWMutex
	filterArgsForCall []struct {
		arg1 string
	}
	filterReturns struct {
		result1 backend.ProductOrderService
	}
	filterReturnsOnCall map[int]struct {
		result1 backend.ProductOrderService
	}
	IDStub        func(int) backend.ProductOrderService
	iDMutex       sync.RWMutex
	iDArgsForCall []struct {
		arg1 int
	}
	iDReturns struct {
		result1 backend.ProductOrderService
	}
	iDReturnsOnCall map[int]struct {
		result1 backend.ProductOrderService
	}
	MaskStub        func(string) backend.ProductOrderService
	maskMutex       sync.RWMutex
	maskArgsForCall []struct {
		arg1 string
	}
	maskReturns struct {
		result1 backend.ProductOrderService
	}
	maskReturnsOnCall map[int]struct {
		result1 backend.ProductOrderService
	}
	PlaceOrderStub        func(interface{}, *bool) (datatypes.Container_Product_Order_Receipt, error)
	placeOrderMutex       sync.RWMutex
	placeOrderArgsForCall []struct {
		arg1 interface{}
		arg2 *bool
	}
	placeOrderReturns struct {
		result1 datatypes.Container_Product_Order_Receipt
		result2 error
	}
	placeOrderReturnsOnCall map[int]struct {
		result1 datatypes.Container_Product_Order_Receipt
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ProductOrderService) Filter(arg1 string) backend.ProductOrderService {
	fake.filterMutex.Lock()
	ret, specificReturn := fake.filterReturnsOnCall[len(fake.filterArgsForCall)]
	fake.filterArgsForCall = append(fake.filterArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Filter", []interface{}{arg1})
	fake.filterMutex.Unlock()
	if fake.FilterStub != nil {
		return fake.FilterStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.filterReturns
	return fakeReturns.result1
}

func (fake *ProductOrderService) FilterCallCount() int {
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	return len(fake.filterArgsForCall)
}

func (fake *ProductOrderService) FilterCalls(stub func(string) backend.ProductOrderService) {
	fake.filterMutex.Lock()
	defer fake.filterMutex.Unlock()
	fake.FilterStub = stub
}

func (fake *ProductOrderService) FilterArgsForCall(i int) string {
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	argsForCall := fake.filterArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ProductOrderService) FilterReturns(result1 backend.ProductOrderService) {
	fake.filterMutex.Lock()
	defer fake.filterMutex.Unlock()
	fake.FilterStub = nil
	fake.filterReturns = struct {
		result1 backend.ProductOrderService
	}{result1}
}

func (fake *ProductOrderService) FilterReturnsOnCall(i int, result1 backend.ProductOrderService) {
	fake.filterMutex.Lock()
	defer fake.filterMutex.Unlock()
	fake.FilterStub = nil
	if fake.filterReturnsOnCall == nil {
		fake.filterReturnsOnCall = make(map[int]struct {
			result1 backend.ProductOrderService
		})
	}
	fake.filterReturnsOnCall[i] = struct {
		result1 backend.ProductOrderService
	}{result1}
}

func (fake *ProductOrderService) ID(arg1 int) backend.ProductOrderService {
	fake.iDMutex.Lock()
	ret, specificReturn := fake.iDReturnsOnCall[len(fake.iDArgsForCall)]
	fake.iDArgsForCall = append(fake.iDArgsForCall, struct {
		arg1 int
	}{arg1})
	fake.recordInvocation("ID", []interface{}{arg1})
	fake.iDMutex.Unlock()
	if fake.IDStub != nil {
		return fake.IDStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.iDReturns
	return fakeReturns.result1
}

func (fake *ProductOrderService) IDCallCount() int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	return len(fake.iDArgsForCall)
}

func (fake *ProductOrderService) IDCalls(stub func(int) backend.ProductOrderService) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = stub
}

func (fake *ProductOrderService) IDArgsForCall(i int) int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	argsForCall := fake.iDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ProductOrderService) IDReturns(result1 backend.ProductOrderService) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	fake.iDReturns = struct {
		result1 backend.ProductOrderService
	}{result1}
}

func (fake *ProductOrderService) IDReturnsOnCall(i int, result1 backend.ProductOrderService) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	if fake.iDReturnsOnCall == nil {
		fake.iDReturnsOnCall = make(map[int]struct {
			result1 backend.ProductOrderService
		})
	}
	fake.iDReturnsOnCall[i] = struct {
		result1 backend.ProductOrderService
	}{result1}
}

func (fake *ProductOrderService) Mask(arg1 string) backend.ProductOrderService {
	fake.maskMutex.Lock()
	ret, specificReturn := fake.maskReturnsOnCall[len(fake.maskArgsForCall)]
	fake.maskArgsForCall = append(fake.maskArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Mask", []interface{}{arg1})
	fake.maskMutex.Unlock()
	if fake.MaskStub != nil {
		return fake.MaskStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.maskReturns
	return fakeReturns.result1
}

func (fake *ProductOrderService) MaskCallCount() int {
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	return len(fake.maskArgsForCall)
}

func (fake *ProductOrderService) MaskCalls(stub func(string) backend.ProductOrderService) {
	fake.maskMutex.Lock()
	defer fake.maskMutex.Unlock()
	fake.MaskStub = stub
}

func (fake *ProductOrderService) MaskArgsForCall(i int) string {
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	argsForCall := fake.maskArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ProductOrderService) MaskReturns(result1 backend.ProductOrderService) {
	fake.maskMutex.Lock()
	defer fake.maskMutex.Unlock()
	fake.MaskStub = nil
	fake.maskReturns = struct {
		result1 backend.ProductOrderService
	}{result1}
}

func (fake *ProductOrderService) MaskReturnsOnCall(i int, result1 backend.ProductOrderService) {
	fake.maskMutex.Lock()
	defer fake.maskMutex.Unlock()
	fake.MaskStub = nil
	if fake.maskReturnsOnCall == nil {
		fake.maskReturnsOnCall = make(map[int]struct {
			result1 backend.ProductOrderService
		})
	}
	fake.maskReturnsOnCall[i] = struct {
		result1 backend.ProductOrderService
	}{result1}
}

func (fake *ProductOrderService) PlaceOrder(arg1 interface{}, arg2 *bool) (datatypes.Container_Product_Order_Receipt, error) {
	fake.placeOrderMutex.Lock()
	ret, specificReturn := fake.placeOrderReturnsOnCall[len(fake.placeOrderArgsForCall)]
	fake.placeOrderArgsForCall = append(fake.placeOrderArgsForCall, struct {
		arg1 interface{}
		arg2 *bool
	}{arg1, arg2})
	fake.recordInvocation("PlaceOrder", []interface{}{arg1, arg2})
	fake.placeOrderMutex.Unlock()
	if fake.PlaceOrderStub != nil {
		return fake.PlaceOrderStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.placeOrderReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ProductOrderService) PlaceOrderCallCount() int {
	fake.placeOrderMutex.RLock()
	defer fake.placeOrderMutex.RUnlock()
	return len(fake.placeOrderArgsForCall)
}

func (fake *ProductOrderService) PlaceOrderCalls(stub func(interface{}, *bool) (datatypes.Container_Product_Order_Receipt, error)) {
	fake.placeOrderMutex.Lock()
	defer fake.placeOrderMutex.Unlock()
	fake.PlaceOrderStub = stub
}

func (fake *ProductOrderService) PlaceOrderArgsForCall(i int) (interface{}, *bool) {
	fake.placeOrderMutex.RLock()
	defer fake.placeOrderMutex.RUnlock()
	argsForCall := fake.placeOrderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ProductOrderService) PlaceOrderReturns(result1 datatypes.Container_Product_Order_Receipt, result2 error) {
	fake.placeOrderMutex.Lock()
	defer fake.placeOrderMutex.Unlock()
	fake.PlaceOrderStub = nil
	fake.placeOrderReturns = struct {
		result1 datatypes.Container_Product_Order_Receipt
		result2 error
	}{result1, result2}
}

func (fake *ProductOrderService) PlaceOrderReturnsOnCall(i int, result1 datatypes.Container_Product_Order_Receipt, result2 error) {
	fake.placeOrderMutex.Lock()
	defer fake.placeOrderMutex.Unlock()
	fake.PlaceOrderStub = nil
	if fake.placeOrderReturnsOnCall == nil {
		fake.placeOrderReturnsOnCall = make(map[int]struct {
			result1 datatypes.Container_Product_Order_Receipt
			result2 error
		})
	}
	fake.placeOrderReturnsOnCall[i] = struct {
		result1 datatypes.Container_Product_Order_Receipt
		result2 error
	}{result1, result2}
}

func (fake *ProductOrderService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.filterMutex.RLock()
	defer fake.filterMutex.RUnlock()
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	fake.maskMutex.RLock()
	defer fake.maskMutex.RUnlock()
	fake.placeOrderMutex.RLock()
	defer fake.placeOrderMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ProductOrderService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ backend.ProductOrderService = new(ProductOrderService)
